<nav class="navbar navbar-inverse" style="margin:0px;">
  <div class="container-fluid">
    <div class="navbar-header">
    <button style="height:20px;" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
    </button>
    <a class="navbar-brand" href="index.php">Map</a>
	<a class="navbar-brand" href="createGroup.php">Group</a>
    </div>
    <div class="collapse navbar-collapse"  id="myNavbar">
      <ul class="nav navbar-nav">
		<li ><a href="profile.php">Profile</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="login.php"></span>Sign out</a></li>
      </ul>
    </div>
  </div>
</nav>

